import { NextResponse } from 'next/server';
import { db } from '@/db'; // Import Drizzle ORM database connection
import { interviewsTable, questionsTable, ratingsTable, roundsTable } from '@/db/schema'; // Import schema

// Define types for related data
type Question = {
  id?: number; // Optional because it's generated by the database
  type: 'behavioral' | 'technical';
  question: string;
  leetcodeLink?: string | null;
};

type Rating = {
  id?: number; // Optional because it's generated by the database
  category: string;
  score: number;
};

type Round = {
  id?: number; // Optional because it's generated by the database
  roundType: string;
  roundDate: string;
  experience: string;
};

type InterviewRequestBody = {
  company: string;
  interviewDate: string;
  jobOffer: boolean;
  overallExperience: string;
  questions?: Question[];
  ratings?: Rating[];
  rounds?: Round[];
};

// GET handler: Fetch all interviews and their related data
export async function GET() {
  try {
    // Fetch main interviews
    const interviews = await db.select().from(interviewsTable);

    // Fetch related questions
    const questions = await db.select().from(questionsTable);

    // Fetch related ratings
    const ratings = await db.select().from(ratingsTable);

    // Fetch related rounds
    const rounds = await db.select().from(roundsTable);

    // Normalize the result into grouped data
    const result = interviews.map((interview) => ({
      id: interview.id,
      company: interview.company,
      interviewDate: interview.interviewDate,
      jobOffer: !!interview.jobOffer, // Convert to boolean
      overallExperience: interview.overallExperience,
      questions: questions
        .filter((q) => q.interviewId === interview.id)
        .map((q) => ({
          id: q.id,
          type: q.type,
          question: q.question,
          leetcodeLink: q.leetcodeLink,
        })),
      ratings: ratings
        .filter((r) => r.interviewId === interview.id)
        .map((r) => ({
          id: r.id,
          category: r.category,
          score: r.score,
        })),
      rounds: rounds
        .filter((ro) => ro.interviewId === interview.id)
        .map((ro) => ({
          id: ro.id,
          roundType: ro.roundType,
          roundDate: ro.roundDate,
          experience: ro.experience,
        })),
    }));

    return NextResponse.json(result, { status: 200 });
  } catch (error) {
    console.error('Error fetching interviews:', error);
    return NextResponse.json(
      { success: false, message: 'Failed to fetch data.' },
      { status: 500 }
    );
  }
}

// POST handler: Add a new interview with related data
export async function POST(req: Request) {
  try {
    const body: InterviewRequestBody = await req.json();

    // Validate the main interview data
    if (!body.company || !body.interviewDate) {
      return NextResponse.json(
        { success: false, message: 'Invalid interview data.' },
        { status: 400 }
      );
    }

    // Insert the main interview record and return its ID
    const [newInterview] = await db
      .insert(interviewsTable)
      .values({
        company: body.company,
        interviewDate: body.interviewDate,
        jobOffer: body.jobOffer,
        overallExperience: body.overallExperience,
      })
      .returning();

    const interviewId = newInterview.id;

    // Save related questions
    if (body.questions && body.questions.length > 0) {
      await db.insert(questionsTable).values(
        body.questions.map((question) => ({
          interviewId,
          type: question.type,
          question: question.question,
          leetcodeLink: question.leetcodeLink || null,
        }))
      );
    }

    // Save related ratings
    if (body.ratings && body.ratings.length > 0) {
      await db.insert(ratingsTable).values(
        body.ratings.map((rating) => ({
          interviewId,
          category: rating.category,
          score: rating.score,
        }))
      );
    }

    // Save related rounds
    if (body.rounds && body.rounds.length > 0) {
      await db.insert(roundsTable).values(
        body.rounds.map((round) => ({
          interviewId,
          roundType: round.roundType,
          roundDate: round.roundDate,
          experience: round.experience,
        }))
      );
    }

    return NextResponse.json(
      { success: true, message: 'Interview and related data saved successfully.' },
      { status: 201 }
    );
  } catch (error) {
    console.error('Error saving interview data:', error);
    return NextResponse.json(
      { success: false, message: 'Failed to save data.' },
      { status: 500 }
    );
  }
}
